name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, develop ]

jobs:
  integration:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [17.x]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint:ts

      - name: Run Stylelint
        run: yarn stylelint:scss

      - name: Run unit tests
        run: yarn test:unit
